version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        until nc -z postgres 5432; do sleep 1; done &&
        echo 'PostgreSQL started' &&
        yarn prisma generate &&
        yarn prisma migrate dev --name init &&
        yarn prisma:seed &&
        yarn start:dev
      "
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
