# Base image
FROM node:20-alpine

# Install yarn
RUN apk add --no-cache yarn

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json yarn.lock ./

# Install dependencies including devDependencies
RUN yarn install

# Bundle app source
COPY . .

# Generate Prisma Client
RUN yarn prisma generate

# Expose port
EXPOSE 3001

# Start the server in development mode
CMD ["yarn", "start:dev"]